In [2]:
# 1. Импортировать NumPy
import numpy as np

In [41]:
# 1.1 Создать массив 10 x 10 со случайными значениями от 1 до 100(int64)
a = np.random.randint(1, 100, (10, 10))
print("Создать массив 10 x 10 со случайными значениями от 1 до 100(int64)")
print(a)
# 1.2 найти среднее значение всех элементов массива np.mean()
print("")
print("1.2 найти среднее значение всех элементов массива np.mean()")
print(np.average(a))
# 1.3 найти среднее значение всех элементов для каждой строки   np.mean()
# и добавить как новый столбец
b = np.mean(a, axis = 0)
print()
print("1.3 найти среднее значение всех элементов для каждой строки np.mean()")
print(b)
c = np.vstack((a, b))
print()
print("и добавить как новый столбец")
print(c)
# 1.4 найти сумму значение всех элементов для каждого столбца   np.sum()
# и добавить как новую строку, учитывая результат 1.3
d = np.sum(a, axis = 1)
print()
print("1.4 найти сумму значение всех элементов для каждого столбца   np.sum()")
print(d)
e = np.vstack((c, d))
print()
print("и добавить как новую строку, учитывая результат 1.3")
print(e)

Создать массив 10 x 10 со случайными значениями от 1 до 100(int64)
[[91 36 63 49 92 80 45 69 65 86]
 [34 93 84 76  8 44 84 16 72 50]
 [50  7 23 38 34  1 47 50 65 28]
 [21 20  6 89 45 46 16 75 42 96]
 [70 35 73 31 67 35 88 59 63 45]
 [60 82 59 34 40 83 88 78 86 96]
 [96 64 32 99 29 12 77 81 26 21]
 [55 77 94 40 88 86 15 75 85 44]
 [76 26 46 67 34 76 97 37 56 43]
 [77 32 25 84  4 24 94 26 69 37]]

1.2 найти среднее значение всех элементов массива np.mean()
55.34

1.3 найти среднее значение всех элементов для каждой строки np.mean()
[63.  47.2 50.5 60.7 44.1 48.7 65.1 56.6 62.9 54.6]

и добавить как новый столбец
[[91.  36.  63.  49.  92.  80.  45.  69.  65.  86. ]
 [34.  93.  84.  76.   8.  44.  84.  16.  72.  50. ]
 [50.   7.  23.  38.  34.   1.  47.  50.  65.  28. ]
 [21.  20.   6.  89.  45.  46.  16.  75.  42.  96. ]
 [70.  35.  73.  31.  67.  35.  88.  59.  63.  45. ]
 [60.  82.  59.  34.  40.  83.  88.  78.  86.  96. ]
 [96.  64.  32.  99.  29.  12.  77.  81.  26.  21. ]
 [55.  77. 

In [43]:
# 2. Создать матрицу 7x7 с значениями 1,2,3,4,5,6,7 по главной диагонали, остальные нули.
#    С помощью функции np.diag() и без(используя broadcasting)
a = np.diag([1,2,3,4,5,6,7])
a

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 7]])

In [8]:
# 3. Создать случайную матрицу 5x7 целых чисел от 1 до 100 и поменять местами 3 и 5 колонки

In [63]:
a = np.random.randint(1, 100, (5, 7))
print(a)
a[:, [4, 2]] = a[:, [2, 4]]
print(a)

[[93 95 92 29 86 31 10]
 [70 50 51 71 87 77 82]
 [55 30 53 38 53 10 31]
 [21 30  9 52 44 92  2]
 [37 92 46 14 78 12  6]]
[[93 95 86 29 92 31 10]
 [70 50 87 71 51 77 82]
 [55 30 53 38 53 10 31]
 [21 30 44 52  9 92  2]
 [37 92 78 14 46 12  6]]
