# Программирование на языке Python. 
# Уровень 4. Анализ и визуализация данных на языке. 
## Библиотеки numpy, pandas, matplotlib

In [42]:
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all" 
np.set_printoptions(linewidth=110)

## Булево индексирование

In [2]:
colors = np.array(['Red', 'Green', 'Blue', 'Red', 'Blue', 'Green', 'Green'])
colors

array(['Red', 'Green', 'Blue', 'Red', 'Blue', 'Green', 'Green'],
      dtype='<U5')

In [3]:
colors.shape

(7,)

In [4]:
colors.dtype.name

'str160'

In [5]:
# np.random.seed(<value>) фиксирует значения случайной выборки
np.random.seed(0)  
data = np.random.randn(7, 4)
data

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385]])

In [6]:
colors

array(['Red', 'Green', 'Blue', 'Red', 'Blue', 'Green', 'Green'],
      dtype='<U5')

In [7]:
colors == 'Red'

array([ True, False, False,  True, False, False, False])

In [8]:
colors == 'Red'

array([ True, False, False,  True, False, False, False])

In [9]:
data

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385]])

In [10]:
data[colors == 'Red']   # тоже самое, что и data[colors == 'Red', :]

array([[1.76405235, 0.40015721, 0.97873798, 2.2408932 ],
       [0.76103773, 0.12167502, 0.44386323, 0.33367433]])

In [11]:
data[[0, 3]]  ## Тот же результат, но явно указываем какие индексы брать для строк

array([[1.76405235, 0.40015721, 0.97873798, 2.2408932 ],
       [0.76103773, 0.12167502, 0.44386323, 0.33367433]])

In [12]:
## Применяем булево индексирование
data[(colors == 'Red') | (colors == 'Green')]   ## | это логическое "ИЛИ"

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385]])

In [13]:
## Применяем булево индексирование
data[(colors == 'Red') | (colors == 'Green'), :]   ## data[[0, 1, 3, 5, 6], :]

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385]])

In [14]:
data[colors == 'Red', 2:]

array([[0.97873798, 2.2408932 ],
       [0.44386323, 0.33367433]])

In [15]:
data[colors == 'Red', 3]

array([2.2408932 , 0.33367433])

In [16]:
data

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385]])

In [26]:
# Здесь не 4 элемента, а 2
data[colors == 'Red', np.array([True, False, False, True])]

array([1.76405235, 0.33367433])

In [27]:
res = data[colors == 'Red']; res

array([[1.76405235, 0.40015721, 0.97873798, 2.2408932 ],
       [0.76103773, 0.12167502, 0.44386323, 0.33367433]])

In [28]:
res[:, np.array([False, False, True, True])]

array([[0.97873798, 2.2408932 ],
       [0.44386323, 0.33367433]])

In [29]:
data[colors == 'Red'][:, np.array([False, True, True, True])]

array([[0.40015721, 0.97873798, 2.2408932 ],
       [0.12167502, 0.44386323, 0.33367433]])

In [30]:
(colors != 'Red') 

array([False,  True,  True, False,  True,  True,  True])

In [31]:
data[colors != 'Red']

array([[ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385]])

**and** и **or** не работают, поэтому нужны: **&**(и), **|**(или), **^**(xor), **~**(not)

In [32]:
mask = (colors == 'Red') | (colors == 'Blue'); mask  

array([ True, False,  True,  True,  True, False, False])

In [33]:
mask.dtype

dtype('bool')

In [34]:
data[mask] # Всегда возвращается копия!

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574]])

In [35]:
data

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385]])

In [36]:
data > 0

array([[ True,  True,  True,  True],
       [ True, False,  True, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True, False,  True, False],
       [False,  True,  True, False],
       [ True, False,  True, False]])

In [37]:
data[data > 0]

array([1.76405235, 0.40015721, 0.97873798, 2.2408932 , 1.86755799,
       0.95008842, 0.4105985 , 0.14404357, 1.45427351, 0.76103773,
       0.12167502, 0.44386323, 0.33367433, 1.49407907, 0.3130677 ,
       0.6536186 , 0.8644362 , 2.26975462, 0.04575852])

In [38]:
# Для элементов со значением индекса True изменить значение на 0
data[data > 0] = 0 
data

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        , -0.97727788,  0.        , -0.15135721],
       [-0.10321885,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        , -0.20515826,  0.        , -0.85409574],
       [-2.55298982,  0.        ,  0.        , -0.74216502],
       [ 0.        , -1.45436567,  0.        , -0.18718385]])

In [39]:
data[colors != 'Green'] = 5
data

array([[ 5.        ,  5.        ,  5.        ,  5.        ],
       [ 0.        , -0.97727788,  0.        , -0.15135721],
       [ 5.        ,  5.        ,  5.        ,  5.        ],
       [ 5.        ,  5.        ,  5.        ,  5.        ],
       [ 5.        ,  5.        ,  5.        ,  5.        ],
       [-2.55298982,  0.        ,  0.        , -0.74216502],
       [ 0.        , -1.45436567,  0.        , -0.18718385]])

### Практика

Есть массив, нужно вывести элементы, согласно условию:
1. Вывести все элементы кратные 3
2. Вывести все элементы кратные 5
3. Вывести все элементы кратные и 3 и 5
4. Вывести все элементы кратные 3 или 5, кроме четных 

`&` - логическое `И`  

`|` - логическое `ИЛИ`

In [41]:
np.random.seed(345)
vector = np.random.randint(1, 100, size=20)
vector

array([25, 81, 84, 80, 10, 30, 43, 76, 25, 69, 30,  4,  5, 43, 98, 24, 81, 74, 87, 20])

### Решение

In [43]:
# Variant 1
vector[vector % 3 == 0]
vector[vector % 5 == 0]
vector[(vector % 3 == 0) & (vector % 5 == 0)]
vector[((vector % 3 == 0) | (vector % 5 == 0)) & (vector % 2 != 0)]

array([81, 84, 30, 69, 30, 24, 81, 87])

array([25, 80, 10, 30, 25, 30,  5, 20])

array([30, 30])

array([25, 81, 25, 69,  5, 81, 87])

In [44]:
# Variant 2
vector
# Вывести все элементы кратные 3
vector[~(vector % 3).astype(bool)]  # 0 -> False, все, что не нуль -> True
# Вывести все элементы кратные 5
vector[~(vector % 5).astype(bool)] 

array([25, 81, 84, 80, 10, 30, 43, 76, 25, 69, 30,  4,  5, 43, 98, 24, 81, 74, 87, 20])

array([81, 84, 30, 69, 30, 24, 81, 87])

array([25, 80, 10, 30, 25, 30,  5, 20])

---

### Скалярное произведение и функция np.tile()

In [45]:
a1 = np.full((3, 5), 3)
a2 = np.arange(10).reshape(5, 2)

In [46]:
a1

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [47]:
a2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [48]:
a1 @ a2     # скалярное произведение

array([[60, 75],
       [60, 75],
       [60, 75]])

In [50]:
a1.dot(a2) # скалярное произведение с тем же результатом

array([[60, 75],
       [60, 75],
       [60, 75]])

In [51]:
## Создание двух двумерных массивов с размерностями 9х1 и 1х4
x, y = np.ogrid[1:10, 1:5]

In [52]:
x

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [53]:
y

array([[1, 2, 3, 4]])

In [54]:
z = x * y
z

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16],
       [ 5, 10, 15, 20],
       [ 6, 12, 18, 24],
       [ 7, 14, 21, 28],
       [ 8, 16, 24, 32],
       [ 9, 18, 27, 36]])

In [55]:
## Копирует значения несколько раз и результат в виде flat массива
z.repeat(2)

array([ 1,  1,  2,  2,  3,  3,  4,  4,  2,  2,  4,  4,  6,  6,  8,  8,  3,  3,  6,  6,  9,  9, 12, 12,  4,
        4,  8,  8, 12, 12, 16, 16,  5,  5, 10, 10, 15, 15, 20, 20,  6,  6, 12, 12, 18, 18, 24, 24,  7,  7,
       14, 14, 21, 21, 28, 28,  8,  8, 16, 16, 24, 24, 32, 32,  9,  9, 18, 18, 27, 27, 36, 36])

In [56]:
mas3 = np.arange(20, 26).reshape(2, 3)
mas3

array([[20, 21, 22],
       [23, 24, 25]])

In [57]:
# Создает новый массив, увеличенный в нужное количество раз по каждой оси
np.tile(mas3, (3, 2))

array([[20, 21, 22, 20, 21, 22],
       [23, 24, 25, 23, 24, 25],
       [20, 21, 22, 20, 21, 22],
       [23, 24, 25, 23, 24, 25],
       [20, 21, 22, 20, 21, 22],
       [23, 24, 25, 23, 24, 25]])

#### Задача №1:
Создать массив(8x8), заполненный нулями и единицами в шахматном порядке.  
С использованием фукции **np.tile()** и **слайсов**.

In [61]:
# Variant 1
np.tile(np.eye(2, dtype=np.int8), (4, 4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]], dtype=int8)

In [59]:
# Variant 2
arr = np.zeros((8, 8), dtype=np.int8)
arr[::2, ::2] = arr[1::2, 1::2] = 1
arr

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]], dtype=int8)

#### Задача №2
Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [62]:
array = np.random.randint(0, 10, (5, 4)); array

array([[8, 0, 3, 1],
       [5, 7, 4, 5],
       [4, 0, 8, 5],
       [6, 3, 3, 4],
       [2, 8, 5, 2]])

In [63]:
array[(array > 3) & (array < 8)] *= -1
array

array([[ 8,  0,  3,  1],
       [-5, -7, -4, -5],
       [-4,  0,  8, -5],
       [-6,  3,  3, -4],
       [ 2,  8, -5,  2]])

## Fancy indexing 

In [64]:
a = np.full((4, 8), np.arange(8))
a

array([[0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7]])

In [65]:
a = a.T

In [66]:
a

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7]])

In [67]:
a[[4, 3, 0, 6]] # Изменяем порядок выдачи строк с указанными индексами

array([[4, 4, 4, 4],
       [3, 3, 3, 3],
       [0, 0, 0, 0],
       [6, 6, 6, 6]])

In [68]:
a[[-3, -5, -7]]

array([[5, 5, 5, 5],
       [3, 3, 3, 3],
       [1, 1, 1, 1]])

In [69]:
a = np.arange(32).reshape((8, 4)); a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [70]:
a[:, [-1, 1]]

array([[ 3,  1],
       [ 7,  5],
       [11,  9],
       [15, 13],
       [19, 17],
       [23, 21],
       [27, 25],
       [31, 29]])

#### Но здесь по-другому!!!

In [71]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [72]:
# (1, 0), (5, 3), (7, 1), (2, 2) это индексы элементов
a[[1, 5, 7, 2], [0, 3, 1, 2]] 

array([ 4, 23, 29, 10])

In [74]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [73]:
a[[1, 5, 7, 2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

#### Работа с осями с помощью функции np.ix_()

In [ ]:
a

In [75]:
a
a[[1, 5, 7, 2]]
## Работа с осями
a[np.ix_([1, 5, 7, 2], [0, 0, 3, 1, 2, 0])]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

array([[ 4,  4,  7,  5,  6,  4],
       [20, 20, 23, 21, 22, 20],
       [28, 28, 31, 29, 30, 28],
       [ 8,  8, 11,  9, 10,  8]])

In [76]:
# Изменение порядка осей. В данном случае тоже самое, что и transpose()
a[np.ix_([1, 5, 7, 2], [0, 0, 3, 1, 2, 0])].swapaxes(1, 0) 

array([[ 4, 20, 28,  8],
       [ 4, 20, 28,  8],
       [ 7, 23, 31, 11],
       [ 5, 21, 29,  9],
       [ 6, 22, 30, 10],
       [ 4, 20, 28,  8]])

### Функции np.put() и np.take()

In [77]:
a = np.arange(16) ** 2
a = a.reshape(4, 4)
print(a)
print(a.ravel())

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]]
[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225]


In [78]:
a
## Индексы вектор-строки (плоские индексы)
b = a.take([3, 5, 7, 15]); b

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]])

array([  9,  25,  49, 225])

In [79]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]])

In [80]:
a.take([1, 13])

array([  1, 169])

In [81]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]])

In [82]:
## Меняем значения у элементов с индексами 2 и 10
a.put([2, 10], [33, 44]); a   # Индексы вектор-строки

array([[  0,   1,  33,   9],
       [ 16,  25,  36,  49],
       [ 64,  81,  44, 121],
       [144, 169, 196, 225]])

In [83]:
a2d = np.random.randint(50, size=[3, 5]); a2d

array([[43, 44, 14, 11, 12],
       [ 3, 16, 11, 21, 41],
       [37, 46, 23,  7, 22]])

In [84]:
a2d.shape

(3, 5)

In [85]:
a2d.put([0, (1 * 5 + 1), (2 * 5 + 2), (1 * 5 + 3), 4], [100, 101, 102, 103, 104])
a2d

array([[100,  44,  14,  11, 104],
       [  3, 101,  11, 103,  41],
       [ 37,  46, 102,   7,  22]])

In [86]:
a2d
## Индекс минимального элемента массива-ленточки(flatten)
min_idx = np.argmin(a2d);min_idx 

array([[100,  44,  14,  11, 104],
       [  3, 101,  11, 103,  41],
       [ 37,  46, 102,   7,  22]])

5

In [87]:
a2d.shape

(3, 5)

In [88]:
index = min_idx // a2d.shape[1], min_idx % a2d.shape[1]; index

(1, 0)

In [89]:
a2d[index]

3

In [90]:
## Изменяет значение линейного индекса в индекс нужной размерности
np.unravel_index(min_idx, a2d.shape)

(1, 0)

In [91]:
max_idx = np.argmax(a2d);max_idx  ## Индекс максимального элемента массива

4

In [92]:
np.unravel_index(max_idx, a2d.shape)

(0, 4)

In [97]:
min_idx = 14

In [96]:
# Изменяет значение линейного индекса в индекс нужной размерности
np.unravel_index(min_idx, (3, 2, 4))  # Вспомнить и проверить

(1, 1, 0)

In [98]:
np.unravel_index(11, (3, 3, 3))  # (1, 0, 2)

(1, 0, 2)

In [100]:
a2d
# Максимальный элемент массива
a2d[np.unravel_index(max_idx, a2d.shape)] 

array([[100,  44,  14,  11, 104],
       [  3, 101,  11, 103,  41],
       [ 37,  46, 102,   7,  22]])

104

In [101]:
# Индекс максимального элемент массива
np.unravel_index(max_idx, (3, 5)) 

(0, 4)

In [102]:
# тот же самый результат, но с помощью flat индекса
np.take(a2d, max_idx)  

104

### Numpy.where()
Векторный вариант тернарного выражения **x if condition else y**

In [103]:
# 1 Вариант
if len('hello') > 4:
    print('good')
else:
    print('bad')

# 2 Вариант
print('good') if len('hello') > 4 else print('bad')
    
res = 'good line' if len('hello') > 5 else 'bad line'
print(res)

i = 5
result = i ** 2 if i > 4 else i ** 3
print(result)

good
good
bad line
25


In [104]:
x_array = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
y_array = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
condition = np.array([True, False, True, True, False])

In [107]:
list(zip(x_array, y_array, condition))

[(1.1, 2.1, True),
 (1.2, 2.2, False),
 (1.3, 2.3, True),
 (1.4, 2.4, True),
 (1.5, 2.5, False)]

In [108]:
x_array
y_array
condition
result = [(x if c else y) for x, y, c in zip(x_array, y_array, condition)]
result

array([1.1, 1.2, 1.3, 1.4, 1.5])

array([2.1, 2.2, 2.3, 2.4, 2.5])

array([ True, False,  True,  True, False])

[1.1, 2.2, 1.3, 1.4, 2.5]

In [109]:
condition
## Результат - это индексы, в которых значение True
np.where(condition)

array([ True, False,  True,  True, False])

(array([0, 2, 3], dtype=int64),)

In [110]:
# Если condition == True тогда берем элемент из x_array, иначе из y_array
result = np.where(condition, x_array, y_array)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [113]:
# Возращает индексы элементов, для которых верно условие (x_array > 1.3) 
idx = np.where(x_array > 1.3); idx

(array([3, 4], dtype=int64),)

In [114]:
x_array[idx]

array([1.4, 1.5])

In [115]:
np.random.seed(5)
a = np.random.randn(4, 4); a

array([[ 0.44122749, -0.33087015,  2.43077119, -0.25209213],
       [ 0.10960984,  1.58248112, -0.9092324 , -0.59163666],
       [ 0.18760323, -0.32986996, -1.19276461, -0.20487651],
       [-0.35882895,  0.6034716 , -1.66478853, -0.70017904]])

In [116]:
np.where(a > 0, 2, -2) # положительные меняем на 2, отрицательные на -2

array([[ 2, -2,  2, -2],
       [ 2,  2, -2, -2],
       [ 2, -2, -2, -2],
       [-2,  2, -2, -2]])

In [117]:
# Для чисел из интервала (-1;0) установим значение 99
np.where((a > -1) & ( a < 0), 99, a)  

array([[ 0.44122749, 99.        ,  2.43077119, 99.        ],
       [ 0.10960984,  1.58248112, 99.        , 99.        ],
       [ 0.18760323, 99.        , -1.19276461, 99.        ],
       [99.        ,  0.6034716 , -1.66478853, 99.        ]])

In [118]:
np.where((a[0] > -1) & ( a[0] < 0), 99, a[0]) 

array([ 0.44122749, 99.        ,  2.43077119, 99.        ])

In [119]:
np.where((a[:, 0] > -1) & ( a[:, 0] < 0), 99, a[:, 0]) 

array([ 0.44122749,  0.10960984,  0.18760323, 99.        ])

In [124]:
# Пример использования функции np.where()
# result = []
# for i in range(n):
#    if condition_1[i] and condition_2[i]:
#        result.append(1)
#    elif condition_1[i]:
#       result.append(2)
#    elif condition_2[i]:
#        result.append(3)
#    else:
#        result.append(4)
condition_1 = np.random.choice([True, False], p=[0.4, 0.6]) # p = probability     
condition_2 = np.random.choice([True, False], p=[0.4, 0.6]) # вероятности
print(condition_1, condition_2)
print(np.where(condition_1 & condition_2, 1, 
         np.where(condition_1, 2, 
                  np.where(condition_2, 3, 4)
                 )
               )
      )            

True False
2
