In [2]:
import numpy as np
import pandas as pd

In [3]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

__Задача №1__

Напишите функцию, которая находит сумму четных элементов на главной 
диагонали квадратной матрицы (именно чётных элементов, а не элементов на чётных позициях!). 
Если чётных элементов нет, то вывести 0

In [4]:
def diag_sum_2k(array):
    diagonal = np.diagonal(array) 
    return np.sum(diagonal[(diagonal % 2 == 0)]) 

In [8]:
# Ваш код
matrix_a = np.random.randint(1, 100, (5, 5))
matrix_a
diag_sum_2k(matrix_a)

array([[81, 31, 98, 97, 47],
       [17, 11, 26,  4, 42],
       [52, 56, 27, 55, 94],
       [ 6, 91, 80, 30, 72],
       [32, 43, 70, 87, 70]])

100

__Задача №2__

Решить задачи при условии, что массив может быть любой размерности:

2.1 Заменить максимальный элемент массива на 1000. (Повторяющихся максимальных элементов нет. Нужно создать такой 2d массив.)    
2.2 Заменить минимальный элемент массива на 0. (Повторяющиеся минимальные элементы есть, поэтому нужно заменить все)

In [54]:
mas = np.random.randint(1, 15, 10)
print(mas)
np.unique(mas, return_counts=True)

[ 9 13  4  1  2 12 10 14  9  8]


(array([ 1,  2,  4,  8,  9, 10, 12, 13, 14]),
 array([1, 1, 1, 1, 2, 1, 1, 1, 1], dtype=int64))

In [9]:
# Решить задачи при условии, что массив может быть любой размерности:
# 2.1 Заменить максимальный элемент массива на 1000. 
# (Повторяющихся максимальных элементов нет. Нужно создать такой 2d массив.) 
# Variant 1
arr2_1 = np.random.choice(np.arange(300), (5, 5), replace=False)
arr2_1
idx = np.argmax(arr2_1)
arr2_1[np.unravel_index(idx, arr2_1.shape)] = 1000
print('После изменений: \n', arr2_1)

array([[183, 213, 118,  66, 135],
       [110, 129,  62,   4, 295],
       [152, 111, 264, 282, 208],
       [ 54, 167, 288, 292, 179],
       [  2, 254,  79, 250, 113]])

После изменений: 
 [[ 183  213  118   66  135]
 [ 110  129   62    4 1000]
 [ 152  111  264  282  208]
 [  54  167  288  292  179]
 [   2  254   79  250  113]]


In [11]:
# Variant 2
arr2_1 = np.random.choice(np.arange(300), (5, 5), replace=False)
arr2_1
idx = np.argmax(arr2_1)
arr2_1.put(idx, 1000)
print('После изменений: \n', arr2_1)

array([[209,  43, 268, 232, 223],
       [297, 144, 135,  58, 204],
       [  0, 205, 101,   6, 190],
       [202, 245, 214, 172,  83],
       [262,  49, 218,  18, 227]])

После изменений: 
 [[ 209   43  268  232  223]
 [1000  144  135   58  204]
 [   0  205  101    6  190]
 [ 202  245  214  172   83]
 [ 262   49  218   18  227]]


In [13]:
# 2.2 Заменить минимальный элемент массива на 0.
# (Повторяющиеся минимальные элементы есть, поэтому нужно заменить все)
mas = np.random.randint(1, 15, (6, 6), dtype=np.int32)
mas
mas[mas == np.min(mas)] = 0
mas 


array([[14, 10, 13, 13,  6,  8],
       [ 4,  3,  6, 12, 10,  4],
       [13, 12,  6,  8,  8, 13],
       [ 9, 14, 10,  9,  3,  4],
       [ 1,  8,  7,  4, 14,  8],
       [13,  8,  1,  5,  9,  4]])

array([[14, 10, 13, 13,  6,  8],
       [ 4,  3,  6, 12, 10,  4],
       [13, 12,  6,  8,  8, 13],
       [ 9, 14, 10,  9,  3,  4],
       [ 0,  8,  7,  4, 14,  8],
       [13,  8,  0,  5,  9,  4]])

__Задача №3*__  

С помощью numpy написать функцию для кодирования массива (Run-length encoding). 
Все подряд повторения элементов функция сжимает в один элемент и 
считает количество повторений. 
Функция возвращает кортеж из двух `numpy`-векторов одинаковой длины. 
Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: 
```
In[1]: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) 
Out[1]: (np.array([1, 2, 3, 1, 5, 2, 3]), np.array([1, 2, 2, 2, 2, 1, 2]))
```

In [68]:
from functools import reduce
from random import randint as rndi
from itertools import groupby

In [69]:
def groupby_encode(a):
    return [x for x, y in groupby(a)], [len(list(y)) for x, y in groupby(a)]

In [70]:
[(x , list(y)) for x, y in groupby(arr)]

[(1, [1]),
 (2, [2, 2]),
 (3, [3, 3]),
 (1, [1, 1]),
 (5, [5, 5]),
 (2, [2]),
 (3, [3, 3])]

In [71]:
groupby_encode(arr)

([1, 2, 3, 1, 5, 2, 3], [1, 2, 2, 2, 2, 1, 2])

In [89]:
GROUPS = 10_000
encode = tuple(reduce(lambda x, y: x + y, [[rndi(1, 10)] * rndi(1, 10) for _ in range(GROUPS)], []))

In [92]:
%timeit res2 = groupby_encode(encode)

6.64 ms ± 220 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [98]:
# Решение на numpy
def encode_two(a):
    # На эту операцию мы тратим много времени
    # a = np.asarray(a)
    # на i-м месте указано, отличается ли a[i] от a[i+1]
    v = np.hstack(((a[:-1] != a[1:]), True))  
    # вывели индексы элементов, которые стоят на границах групп из одинаковых идущих подряд чисел
    z = np.nonzero(np.hstack((True, v)))      
    # diff выводит приращение между номерами, указанными в z
    return a[v], np.diff(z)[0] 

In [95]:
%timeit res3 = encode_two(encode)

4.85 ms ± 164 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [99]:
array_encode = np.array(encode)

In [124]:
%timeit res4 = encode_two(array_encode)

415 µs ± 12.9 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [107]:
def run_length_encoding(arr):
    dif = np.array([1])
    dif = np.insert(dif, 1, np.diff(arr))
    
    numbers = arr[np.nonzero(dif)]

    dif = np.append(dif, 1)

    quantity = np.diff(np.nonzero(dif))
    return (numbers, quantity)

In [123]:
%timeit res5 = encode_two(array_encode)

420 µs ± 20.4 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [122]:
all(res5[0] == res4[0]), all(res5[1] == res4[1])

(True, True)

In [116]:
arr

array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])