In [2]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"     # Вывод всех строк без принтов
# InteractiveShell.ast_node_interactivity = "last"  # Только последний вывод

#### Задача 1

Создать массив 10x10 со случайными значениями(int64):
- Найти минимум и максимум всего массива
- Вывести разницу между max и min для всего массива  
- Вывести разницу между max и min для каждой оси  

In [12]:
# Создать массив 10x10 со случайными значениями(int64)
arr = np.random.randint(1, 100, (10, 10))
arr

array([[93, 99, 87, 44, 31, 34, 64, 28, 28, 91],
       [13,  3, 27, 75, 95, 70, 49, 15, 85, 86],
       [20, 14, 15, 11, 43, 63, 16, 64, 47, 43],
       [25, 91, 54, 23, 11, 53, 49, 39, 53, 74],
       [41, 32, 64,  9, 64,  7,  2, 55, 89, 72],
       [91, 96, 29, 48, 24, 62, 48, 48, 23, 76],
       [34, 85, 18, 97, 64,  6, 42, 71, 68, 75],
       [76, 72,  2, 45, 72, 13, 98, 46, 64, 87],
       [44, 87,  7, 67, 32, 69, 77, 45, 86,  1],
       [33, 50, 14, 25, 53, 73, 12, 66, 83, 39]])

In [13]:
# Найти минимум и максимум всего массива
print('Minimum:', np.min(arr))
print('Maximum:', arr.max())

Minimum: 1
Maximum: 99


In [14]:
# Вывести разницу между max и min для всего массива
np.max(arr) - np.min(arr)

98

In [15]:
# Вывести разницу между max и min для каждой оси
# Разница по строкам
rows = np.max(arr, axis=1) - np.min(arr, axis=1) 
rows
# Разница по столбцам
columns = np.max(arr, axis=0) - np.min(arr, axis=0) 
columns

array([71, 92, 53, 80, 87, 73, 91, 96, 86, 71])

array([80, 96, 85, 88, 84, 67, 96, 56, 66, 90])

In [18]:
# Проверка с помощью функции numpy.ptp(peak-to-peak)
rows_by_ptp = np.ptp(arr, axis=1)
rows_by_ptp
columns_by_ptp = np.ptp(arr, axis=0)
columns_by_ptp

array([71, 92, 53, 80, 87, 73, 91, 96, 86, 71])

array([80, 96, 85, 88, 84, 67, 96, 56, 66, 90])