## Библиотека numpy - практика

In [14]:
# загрузите необходимые библиотеки
import numpy as np
np.set_printoptions(linewidth=120)

### Задачи

Решите следующие задачи без использования циклов, с минимальным количеством строк.

1 . Решите следующие небольшие задачи

In [2]:
# 1.1 создайте список натуральных чисел от 0 до 47
c = np.arange(48)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47]


In [4]:
# 1.2 преобразуйте его в матрицу размером 12x4 
c = c.reshape(12, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47]])

In [5]:
# 1.3 преобразуйте эту матрицу в трехмерную матрицу размером 3x4x4
c.shape = (3, 4, 4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

2 . Американские коллеги прислали архив с наблюдениями температуры, но вот незадача: температура там указана в Фаренгейтах. Формула для перевода: $\frac{C}{5}=\frac{F - 32}{9}$

In [18]:
temps_F = np.array([0, 100, 99.1, 32, 44, 241, 10, 15, 20])
temps_C = (temps_F - 32) * 5 / 9
print(temps_C)

[-17.778  37.778  37.278   0.      6.667 116.111 -12.222  -9.444  -6.667]


In [16]:
np.set_printoptions(precision=3)

In [17]:
np.round((temps_F - 32) * 5 / 9, 2)

array([-17.78,  37.78,  37.28,   0.  ,   6.67, 116.11, -12.22,  -9.44,  -6.67])

In [19]:
%precision 5
temps_C

array([-17.77778,  37.77778,  37.27778,   0.     ,   6.66667, 116.11111, -12.22222,  -9.44444,  -6.66667])