In [10]:
import numpy as np

__Задача №1__

Напишите функцию, которая находит сумму четных элементов на главной 
диагонали квадратной матрицы (именно чётных элементов, а не элементов на чётных позициях!). 
Если чётных элементов нет, то вывести 0

In [48]:
# Ваш код
matrix = np.arange(25).reshape(5, 5)
print(matrix)

def sum_diagonal_enum(mtrx: np.ndarray) -> int:
    diagonal = np.diagonal(mtrx)
    print(diagonal)
    enum = diagonal[diagonal % 2 == 0]
    print(enum)
    sum_enum = np.sum(enum)
    return sum_enum if sum_enum > 0 else 0

print(sum_diagonal_enum(matrix))


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[ 0  6 12 18 24]
[ 0  6 12 18 24]
60


__Задача №2__

Решить задачи при условии, что массив может быть любой размерности:

2.1 Заменить максимальный элемент массива на 1000. (Повторяющихся максимальных элементов нет. Нужно создать такой 2d массив.)    
2.2 Заменить минимальный элемент массива на 0. (Повторяющиеся минимальные элементы есть, поэтому нужно заменить все)

In [86]:
mas = np.random.randint(1, 1000, 10)
print(mas)
mas_unq = np.unique(mas)
print(mas_unq)
max = np.max(mas_unq)
print(max)

mas_unq[np.where(mas_unq == max)] = 1000
print(mas_unq)
#np.unique(mas, return_counts=True)

[155 687 127 471 840  54 831 698 586 410]
[ 54 127 155 410 471 586 687 698 831 840]
840
[  54  127  155  410  471  586  687  698  831 1000]


__Задача №3*__  

С помощью numpy написать функцию для кодирования массива (Run-length encoding). 
Все подряд повторения элементов функция сжимает в один элемент и 
считает количество повторений. 
Функция возвращает кортеж из двух `numpy`-векторов одинаковой длины. 
Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: 
```
In[1]: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) 
Out[1]: (np.array([1, 2, 3, 1, 5, 2, 3]), np.array([1, 2, 2, 2, 2, 1, 2]))
```

In [169]:
# Ваш код 
# Подсказка, что использовать:
# diff() nonzero() where()
arr = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3, 3])
print(f"arr: {arr}")
arr1 = np.append(arr, 100)
print(f"arr1: {arr1}")
diff = np.diff(arr1)
print(f"diff: {diff}")
zero = np.nonzero(diff)
print(f"zero: {zero}")
# array[zero]
where1 = np.where(np.diff(arr1) != 0)
print(f"where1: {where1}")
result = arr1[where1]
print(f"result: {result}")
#np.add(arr, diff)
#arr - diff
np.diff(diff)


arr: [1 2 2 3 3 1 1 5 5 2 3 3 3]
arr1: [  1   2   2   3   3   1   1   5   5   2   3   3   3 100]
diff: [ 1  0  1  0 -2  0  4  0 -3  1  0  0 97]
zero: (array([ 0,  2,  4,  6,  8,  9, 12]),)
where1: (array([ 0,  2,  4,  6,  8,  9, 12]),)
result: [1 2 3 1 5 2 3]


array([-1,  1, -1, -2,  2,  4, -4, -3,  4, -1,  0, 97])