#### Нужные параметры для вывода всех значений, а не только последнего(по умолчанию)

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"     # Вывод всех строк без принтов
# InteractiveShell.ast_node_interactivity = "last"  # Только последний вывод

### Изменение размерности

Функции __ravel()__, __reshape()__, __flatten()__ и __resize()__ 

In [2]:
import numpy as np

In [10]:
b = np.arange(24).reshape(2, 3, 4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [11]:
# Результат - одномерный массив
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [12]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [13]:
b.flatten() # возращает копию

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [14]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [15]:
b.shape
b.shape = (6, 4)  ## то же самое, что и b.reshape(6, 4)
b.shape

(2, 3, 4)

(6, 4)

In [16]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [18]:
# Транспонирование матрицы: строки -> столбцы, столбцы -> строки
# можно и так b.T
b.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [19]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [20]:
b = np.arange(24).reshape(2, 3, 4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [21]:
b.transpose(1, 2, 0)

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

#### Изменение размера массива

In [22]:
d = np.random.randint(1, 100, (2, 12)); d

array([[19, 11, 85,  9, 56, 80, 13, 80, 72, 97, 61, 63],
       [63, 30, 55, 36, 47, 27, 97, 88, 56, 70, 36, 47]])

In [23]:
# остальные элементы заполнены нулями
d.resize((3, 15), refcheck=False); d

array([[19, 11, 85,  9, 56, 80, 13, 80, 72, 97, 61, 63, 63, 30, 55],
       [36, 47, 27, 97, 88, 56, 70, 36, 47,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [25]:
c = np.arange(24)
c.shape = 8, 3

In [26]:
c.resize(9, 3)
c

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [ 0,  0,  0]])

In [27]:
c.resize?

In [28]:
## Новые элементы массива будут иметь значение 0,
## когда вызываем у массива
c1 = c.copy()
c1.resize(15, 3)
c1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0]])

In [29]:
c.shape
# Новые элементы массива берут значения из старого массива
c2 = np.resize(c, (12, 3))
c2

(9, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [ 0,  0,  0],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

### Добавление элементов. Оси(axes).

In [30]:
a = np.arange(10); a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
a = np.append(a, [1, 3, 4, 4]); a   # Похож на метод extend для списка

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 3, 4, 4])

In [37]:
e = np.arange(12).reshape(3, 4); e

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
e = np.append(e, [[99, 97, 96, 95]], axis=0)  # 0-я ось - это строки 2х мерном массиве
e

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [99, 97, 96, 95]])

In [40]:
e = np.append(e, [[99], [97], [96], [95]], axis=1) # 1-я ось - это столбцы 2х мерном массиве
e

array([[ 0,  1,  2,  3, 99],
       [ 4,  5,  6,  7, 97],
       [ 8,  9, 10, 11, 96],
       [99, 97, 96, 95, 95]])

In [41]:
temp = np.array([[99, 97, 96, 95]]); temp

array([[99, 97, 96, 95]])

In [42]:
temp.shape

(1, 4)

In [43]:
temp1 = np.array([[99], [97], [96], [95]]); temp1

array([[99],
       [97],
       [96],
       [95]])

In [44]:
temp1.shape

(4, 1)

In [59]:
a3d = np.arange(27).reshape(3, 3, 3); a3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [60]:
add_mas = np.arange(100, 109).reshape(1, 3, 3); add_mas

array([[[100, 101, 102],
        [103, 104, 105],
        [106, 107, 108]]])

In [61]:
a3d_new = np.append(a3d, add_mas, axis=0)   # 0-я ось - это глубина
a3d_new 

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8]],

       [[  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17]],

       [[ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26]],

       [[100, 101, 102],
        [103, 104, 105],
        [106, 107, 108]]])

In [62]:
vector = np.array([[4, 5, 6]])
vector, vector.shape

(array([[4, 5, 6]]), (1, 3))

In [63]:
foo = np.append(a3d_new, vector, 0); foo ## Error

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 2 dimension(s)

### Вставка элементов

In [64]:
a = np.arange(10); a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
# 2 - это индекс элемента, но не значение
# при вставке изменился тип элементов на тип массива
a = np.insert(a, 2, np.asarray([99.1, 101.09])); a 

array([  0,   1,  99, 101,   2,   3,   4,   5,   6,   7,   8,   9])

In [66]:
# Вставка в массив NxM
a1 = np.array([[1, 1], [2, 2], [3, 3]])
a1

array([[1, 1],
       [2, 2],
       [3, 3]])

In [68]:
a1

array([[1, 1],
       [2, 2],
       [3, 3]])

In [69]:
np.insert(a1, 4, 5)  # Сейчас массив будет представлен в виде единой ленточки(flatten)

array([1, 1, 2, 2, 5, 3, 3])

In [70]:
# Явно указали ось(измерение), по которой работаем(столбцы)
np.insert(a1, 1, 5, axis=1)

array([[1, 5, 1],
       [2, 5, 2],
       [3, 5, 3]])

In [71]:
a

array([  0,   1,  99, 101,   2,   3,   4,   5,   6,   7,   8,   9])

In [72]:
## Hовые элементы неявно будет преобразованы к типу элементов массива
a = np.insert(a, 6, np.random.randn(10) * 3); a

array([  0,   1,  99, 101,   2,   3,   5,   3,   0,   4,  -2,   0,   2,
        -6,  -5,  -2,   4,   5,   6,   7,   8,   9])

In [75]:
a = np.random.randint(1, 20, (5, 3)); a

array([[19, 17, 18],
       [12, 13, 12],
       [11,  1,  2],
       [14,  2, 16],
       [15, 10,  3]])

In [77]:
new_a = np.insert(a, 2, [20, 21, 22], axis=0); new_a

array([[19, 17, 18],
       [12, 13, 12],
       [20, 21, 22],
       [11,  1,  2],
       [14,  2, 16],
       [15, 10,  3]])

### Удаление элементов

In [78]:
a
np.delete(a, 2, axis=0)

array([[19, 17, 18],
       [12, 13, 12],
       [11,  1,  2],
       [14,  2, 16],
       [15, 10,  3]])

array([[19, 17, 18],
       [12, 13, 12],
       [14,  2, 16],
       [15, 10,  3]])

In [79]:
a
np.delete(a, 2, axis=1)

array([[19, 17, 18],
       [12, 13, 12],
       [11,  1,  2],
       [14,  2, 16],
       [15, 10,  3]])

array([[19, 17],
       [12, 13],
       [11,  1],
       [14,  2],
       [15, 10]])

## Практика

#### Задача 1

Создать массив 10x10 со случайными значениями(int64):
- Найти минимум и максимум всего массива
- Вывести разницу между max и min для всего массива  
- Вывести разницу между max и min для каждой оси  

#### Решение:

In [ ]:
# смотри файл: sol_Task2_practice.ipynb

#### Задача 2 
```
np.random.seed(5)  
```
Дана матрица 4х3, со случайные целыми числами от 1 до 100:  
- найти столбец в котором разница между мин и макс минимальна и удалить его


In [ ]:
# Подсказки, что потребуется
a2d = np.random.randint(1, 50, (4, 3))
print(a2d)
np.argmin(a2d)  # flat индекс минимального элемента

In [ ]:
# Подсказки, что потребуется:
# индекс в размерности массива
np.unravel_index(np.argmin(a2d), a2d.shape)

####  Задача 3. Решить задачу 2 для 3d массива
Дополнение: вырезать прямоугольник, в котором находится нужный столбец, в глубину

In [ ]:
np.random.seed(555)
a3d = np.random.randint(1, 100, (4, 3, 4)); a3d

In [ ]:
np.min(a3d, axis=0) # по глубине

In [ ]:
np.min(a3d, axis=1) # по строкам

In [ ]:
np.min(a3d, axis=2) # по столбцам