In [8]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all" 

#### Задача 2 
```
np.random.seed(5)  
```
Дана матрица 4х3, со случайные целыми числами от 1 до 100:  
- найти столбец в котором разница между мин и макс минимальна и удалить его

In [6]:
# Подсказки, что потребуется
a2d = np.random.randint(1, 50, (4, 3))
print(a2d)
# Подсказка, что можно использовать
# np.argmin(a2d)  # flat индекс минимального элемента

[[ 9 22  5]
 [47 43 31]
 [25 35  2]
 [42 26 36]]


In [9]:
# Подсказки, что потребуется:
# индекс в размерности массива
np.argmin(a2d)
np.unravel_index(np.argmin(a2d), a2d.shape)

8

(2, 2)

In [10]:
print('Вектор разниц между макс и мин по столбцам')
column_diffs = np.max(a2d, axis=0) - np.min(a2d, axis=0)
print(column_diffs)

Вектор разниц между макс и мин по столбцам
[38 21 34]


In [12]:
index_of_min = np.argmin(column_diffs)
print(f'Наименьший элемент: {np.min(column_diffs)} и его плоский (flat) индекс(столбец в исходной матрице): \
{index_of_min}')

Наименьший элемент: 21 и его плоский (flat) индекс(столбец в исходной матрице): 1


In [13]:
a2d_after_del = np.delete(a2d, index_of_min, axis=1)
print(a2d_after_del)

[[ 9  5]
 [47 31]
 [25  2]
 [42 36]]


####  Задача 3. Решить задачу 2 для 3d массива
Дополнение: вырезать прямоугольник, в котором находится нужный столбец, в глубину

In [14]:
np.random.seed(42) 
a3d = np.random.randint(1, 100, (4, 3, 4)); a3d

array([[[52, 93, 15, 72],
        [61, 21, 83, 87],
        [75, 75, 88, 24]],

       [[ 3, 22, 53,  2],
        [88, 30, 38,  2],
        [64, 60, 21, 33]],

       [[76, 58, 22, 89],
        [49, 91, 59, 42],
        [92, 60, 80, 15]],

       [[62, 62, 47, 62],
        [51, 55, 64,  3],
        [51,  7, 21, 73]]])

In [15]:
print('Матрица разниц между макс и мин по столбцам во всех слоях.')
delta_2d = np.max(a3d,  axis=1) - np.min(a3d,  axis=1)
print(delta_2d)

Матрица разниц между макс и мин по столбцам во всех слоях.
[[23 72 73 63]
 [85 38 32 31]
 [43 33 58 74]
 [11 55 43 70]]


In [17]:
flat_idx = np.argmin(delta_2d)
f'{flat_idx = }'
min_col_index = np.unravel_index(flat_idx, delta_2d.shape)
print(f'Наименьший элемент: {np.min(delta_2d)} и его индекс {min_col_index}')

'flat_idx = 12'

Наименьший элемент: 11 и его индекс (3, 0)


In [18]:
a3d_after_del = np.delete(a3d, min_col_index[-1], axis=2)
a3d_after_del

array([[[93, 15, 72],
        [21, 83, 87],
        [75, 88, 24]],

       [[22, 53,  2],
        [30, 38,  2],
        [60, 21, 33]],

       [[58, 22, 89],
        [91, 59, 42],
        [60, 80, 15]],

       [[62, 47, 62],
        [55, 64,  3],
        [ 7, 21, 73]]])

#### Check

In [20]:
a3d = np.random.randint(1, 100, (4, 3, 4)); a3d

array([[[39, 18,  4, 89],
        [60, 14,  9, 90],
        [53,  2, 84, 92]],

       [[60, 71, 44,  8],
        [47, 35, 78, 81],
        [36, 50,  4,  2]],

       [[ 6, 54,  4, 54],
        [93, 63, 18, 90],
        [44, 34, 74, 62]],

       [[14, 95, 48, 15],
        [72, 78, 87, 62],
        [40, 85, 80, 82]]])

In [21]:
np.unravel_index(22, a3d.shape)  # (1, 2, 2)

(1, 2, 2)