In [6]:
# 1. Импортировать NumPy
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all" 
np.set_printoptions(linewidth=100)

In [2]:
# 1.1 Создать массив 10 x 10 со случайными значениями от 1 до 100(int64)
width = height = 10
arr = np.random.randint(1, 100, size=(width, height), dtype=np.int64)
arr


array([[94,  7, 58, 64, 20, 25, 85, 76, 76, 22],
       [85, 20, 42, 38, 17, 88,  6, 64, 91, 92],
       [18, 29, 12, 24, 12, 42, 18, 14, 21, 66],
       [42, 46, 19, 38, 31, 59, 33, 35, 40, 22],
       [81, 46, 89, 95, 48, 28, 18, 71, 20, 72],
       [45, 79, 48, 39, 53, 96,  2, 64, 10, 43],
       [99, 82, 45, 33, 30, 25, 64, 24,  4, 82],
       [ 9, 37, 26, 14, 71, 48, 33, 96, 76, 95],
       [ 8, 95, 20, 31,  3, 52, 81, 72, 55, 10],
       [22, 11, 33, 42, 45, 20,  1, 32, 37, 53]], dtype=int64)

In [3]:
# 1.2 найти среднее значение всех элементов массива np.mean()
avg = np.mean(arr)
avg

44.54

In [4]:
# 1.3 найти среднее значение всех элементов для каждой строки   np.mean()
# и добавить как новый столбец
avg_rows = np.mean(arr, axis=1)
arr_new = np.concatenate((arr, avg_rows.reshape(width, 1)), axis=1)
arr_new

array([[94. ,  7. , 58. , 64. , 20. , 25. , 85. , 76. , 76. , 22. , 52.7],
       [85. , 20. , 42. , 38. , 17. , 88. ,  6. , 64. , 91. , 92. , 54.3],
       [18. , 29. , 12. , 24. , 12. , 42. , 18. , 14. , 21. , 66. , 25.6],
       [42. , 46. , 19. , 38. , 31. , 59. , 33. , 35. , 40. , 22. , 36.5],
       [81. , 46. , 89. , 95. , 48. , 28. , 18. , 71. , 20. , 72. , 56.8],
       [45. , 79. , 48. , 39. , 53. , 96. ,  2. , 64. , 10. , 43. , 47.9],
       [99. , 82. , 45. , 33. , 30. , 25. , 64. , 24. ,  4. , 82. , 48.8],
       [ 9. , 37. , 26. , 14. , 71. , 48. , 33. , 96. , 76. , 95. , 50.5],
       [ 8. , 95. , 20. , 31. ,  3. , 52. , 81. , 72. , 55. , 10. , 42.7],
       [22. , 11. , 33. , 42. , 45. , 20. ,  1. , 32. , 37. , 53. , 29.6]])

In [7]:
# 1.4 найти сумму значение всех элементов для каждого столбца   np.sum()
# и добавить как новую строку, учитывая результат 1.3
sum_columns = np.sum(arr_new, axis=0)
arr_result = np.concatenate((arr_new, sum_columns.reshape(1, -1)), axis=0)
arr_result

array([[ 94. ,   7. ,  58. ,  64. ,  20. ,  25. ,  85. ,  76. ,  76. ,  22. ,  52.7],
       [ 85. ,  20. ,  42. ,  38. ,  17. ,  88. ,   6. ,  64. ,  91. ,  92. ,  54.3],
       [ 18. ,  29. ,  12. ,  24. ,  12. ,  42. ,  18. ,  14. ,  21. ,  66. ,  25.6],
       [ 42. ,  46. ,  19. ,  38. ,  31. ,  59. ,  33. ,  35. ,  40. ,  22. ,  36.5],
       [ 81. ,  46. ,  89. ,  95. ,  48. ,  28. ,  18. ,  71. ,  20. ,  72. ,  56.8],
       [ 45. ,  79. ,  48. ,  39. ,  53. ,  96. ,   2. ,  64. ,  10. ,  43. ,  47.9],
       [ 99. ,  82. ,  45. ,  33. ,  30. ,  25. ,  64. ,  24. ,   4. ,  82. ,  48.8],
       [  9. ,  37. ,  26. ,  14. ,  71. ,  48. ,  33. ,  96. ,  76. ,  95. ,  50.5],
       [  8. ,  95. ,  20. ,  31. ,   3. ,  52. ,  81. ,  72. ,  55. ,  10. ,  42.7],
       [ 22. ,  11. ,  33. ,  42. ,  45. ,  20. ,   1. ,  32. ,  37. ,  53. ,  29.6],
       [503. , 452. , 392. , 418. , 330. , 483. , 341. , 548. , 430. , 557. , 445.4]])

In [10]:
# 2. Создать матрицу 7x7 с значениями 1,2,3,4,5,6,7 по главной диагонали, остальные нули.
#    С помощью функции np.diag() и без(используя broadcasting)

In [13]:
# without broadcasting
a = np.arange(1, 8)
np.diag(a, k=-1)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0]])

In [15]:
# with broadcasting
m = np.eye(7)
res = m * a
res

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0., 0.],
       [0., 0., 0., 4., 0., 0., 0.],
       [0., 0., 0., 0., 5., 0., 0.],
       [0., 0., 0., 0., 0., 6., 0.],
       [0., 0., 0., 0., 0., 0., 7.]])

In [17]:
# 3. Создать случайную матрицу 5x7 целых чисел от 1 до 100 и поменять местами 3 и 5 колонки
m_3 = np.random.randint(1, 100, (5, 7)); m_3

array([[64,  7, 52, 14, 87, 93, 37],
       [64, 16, 33, 16, 75, 36, 81],
       [96, 66, 13, 83, 19, 43, 44],
       [57, 59, 86, 95, 11, 51, 30],
       [13, 51, 45, 54, 70, 91, 21]])

In [18]:
m_3[:, [4, 2]] = m_3[:, [2, 4]]
m_3

array([[64,  7, 87, 14, 52, 93, 37],
       [64, 16, 75, 16, 33, 36, 81],
       [96, 66, 19, 83, 13, 43, 44],
       [57, 59, 11, 95, 86, 51, 30],
       [13, 51, 70, 54, 45, 91, 21]])

In [20]:
a = np.random.randint(1, 100, (5, 7))
print(a)
a=np.insert(a, 5, a[:, 2], axis=1)
a=np.insert(a, 3, a[:, 4], axis=1)
a=np.delete(a, 2, axis=1)
a=np.delete(a, 4, axis=1)
a

[[78 61 66 47 18 10  2]
 [33 30 95 80 47 18 75]
 [ 8 89 94 36 32 97 52]
 [69 77 93 29 66  1 48]
 [64 96 26 80 71 58 71]]


array([[78, 61, 18, 47, 66, 10,  2],
       [33, 30, 47, 80, 95, 18, 75],
       [ 8, 89, 32, 36, 94, 97, 52],
       [69, 77, 66, 29, 93,  1, 48],
       [64, 96, 71, 80, 26, 58, 71]])